# Numerical Computing with Python
### Table of contents:
* [Introduction](##Introduction)
    - [List Vs NumPy](###List_Vs_NumPy)
* [Fundamentals](##Fundamentals)
    - [Dimensions](####Dimensions)
    - [dtype](####dtype)


## Introduction
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.  
- NumPy is fast as it uses Fixed types.
- Numpy operations are implemented in C, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking.

In [1]:
# if you haven't installed NumPy already, uncomment the below line and run this cell:
# %pip install numpy -q

### List_Vs_NumPy

In [2]:
%%time

# let's create a for loop to sum all the numbers in the list

nums = [i for i in range(10_000_00)]
sum_ = 0
for e in range(len(nums)):
    sum_ += e
sum_    


CPU times: user 110 ms, sys: 7.51 ms, total: 117 ms
Wall time: 116 ms


499999500000

In [6]:
%%time

# let's do the same thing with numpy
import numpy as np
np_list = np.arange(10_000_00)
np_list.sum()

CPU times: user 1.69 ms, sys: 2.28 ms, total: 3.97 ms
Wall time: 2.51 ms


499999500000

Time taken by python list: 116ms  
Time taken by NumPy: 2.59ms  
  
as we can see, NumPy arrays are relatively so fast when compared to python lists. why? because in NumPy there is fixed type check where as in Python list uses dynamic type checking means it checks the tyoe of the element present in the list everytime. So it's no surpise that list are slower than NumPy arrays

## Fundamentals
#### Creating an array

In [27]:
array = np.array([1, 2, 3, 4, 5]) # create a numpy array of dimesions 1x5
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create a numpy array of dimesions 3x3
array3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # create a numpy array of dimesions 2x3x3

In [18]:
array

array([1, 2, 3, 4, 5])

In [35]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
# accessing elements in a numpy array
print(array2d[0]) # get the first row
print(array2d[0][1]) # get the second element in the first row

print(array2d[:, 1]) # get the second column

[1 2 3]
2
[2 5 8]


#### Dimensions

In [23]:
# Number of dimensions
print(array.ndim)
print(array2d.ndim)
print(array3d.ndim)

1
2
3


#### dtype
dtype is an attribute of a numpy array, basically dtype allows us to specify the data type of our array.  
various numerical data types are:  
- int
  * int8
  * int16
  * int32
  * int64
- float
  * float16
  * float32
  * float64

by default the data type is of 64 bit.  
changing dtype attribute does benefit a lot in computations like when using lower bit data type it saves memory and obviously the computation is fast.


In [45]:
np.arange(10, dtype='int64') # create a numpy array of dimesions 1x10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])