## Introduction
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.  
- NumPy is fast as it uses Fixed types.
- Numpy operations are implemented in C, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking.

In [1]:
# if you haven't installed NumPy already, uncomment the below line and run this cell:
# %pip install numpy -q

### List Vs NumPy

In [2]:
%%time

# let's create a for loop to sum all the numbers in the list

nums = [i for i in range(10_000_00)]
sum_ = 0
for e in range(len(nums)):
    sum_ += e
sum_    


CPU times: user 78 ms, sys: 4.54 ms, total: 82.5 ms
Wall time: 81.8 ms


499999500000

In [3]:
%%time

# let's do the same thing with numpy
import numpy as np
np_list = np.arange(10_000_00)
np_list.sum()

CPU times: user 999 ms, sys: 51 ms, total: 1.05 s
Wall time: 158 ms


499999500000

time taken by the python list is much more than numpy

as we can see, NumPy arrays are relatively so fast when compared to python lists. why? because in NumPy there is fixed type check where as in Python list uses dynamic type checking means it checks the tyoe of the element present in the list everytime. So it's no surpise that list are slower than NumPy arrays

## Fundamentals
#### Creating an array

In [4]:
array = np.array([1, 2, 3, 4, 5]) # create a numpy array of dimesions 1x5
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create a numpy array of dimesions 3x3
array3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # create a numpy array of dimesions 2x3x3

In [5]:
array

array([1, 2, 3, 4, 5])

In [6]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

#### Accessing Elements

In [8]:
# accessing elements in a numpy array
print(array2d[0]) # get the first row
print(array2d[0][1]) # get the second element in the first row
print(array2d[0, 1]) # get the second element in the first row
print(array2d[:, 1]) # get the second column

[1 2 3]
2
2
[2 5 8]


In [9]:
# accessing elements using negative indices
array2d[-1] # get the last row

array([7, 8, 9])

In [10]:
# get a specific row
array2d[0, :] # get the first row

array([1, 2, 3])

In [11]:
# get a specific column
array2d[:, 2] # get the third column

array([3, 6, 9])

In [12]:
# accessing first and last elements in a 2nd column of a 2d array
array2d[0::2, 1]

array([2, 8])

#### Changing values

In [13]:
array2d[0, 1] = 100 # change the second element in the first row to 100
array2d

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [14]:
# changing multiple elements
array2d[0, :] = 100 # change the first row to 100
array2d

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [15]:
# changing multiple elements with different values
array2d[:, 1] = [100, 200, 300] # change the second column to 100, 200, 300
array2d

array([[100, 100, 100],
       [  4, 200,   6],
       [  7, 300,   9]])

#### Dimensions

In [16]:
# Number of dimensions
print(array.ndim)
print(array2d.ndim)
print(array3d.ndim)

1
2
3


#### Creating different types of arrays

In [17]:
# all zeros matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.full((2, 3), 99) # create a matrix of 2x3 with all elements as 99

array([[99, 99, 99],
       [99, 99, 99]])

In [21]:
np.identity(3, dtype='int32') # create an identity matrix of 3x3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [22]:
np.random.rand(4, 2)
# note: rand() generates random numbers between 0 and 1
# and you cannot pass a tuple, it means you cannot specify the shape of the matrix as a tuple
# to pass a tuple you need to use random_sample()

array([[0.61149151, 0.40347123],
       [0.09187589, 0.72975069],
       [0.71435316, 0.54766109],
       [0.12381836, 0.9173889 ]])

In [23]:
np.random.random_sample((array2d.shape))

array([[0.12583868, 0.56204805, 0.36284734],
       [0.55786519, 0.39570004, 0.52676173],
       [0.43085521, 0.34775997, 0.91339192]])

In [24]:
np.random.randint(20, size=(3, 3)) # create a matrix of 3x3 with random integers between 0 and 20

array([[ 0, 19, 13],
       [ 7,  9,  8],
       [18, 14, 14]])

#### Copying arrays
- be careful when copying arrays.

In [25]:
b = array2d
b[0, 1] = -3
b

array([[100,  -3, 100],
       [  4, 200,   6],
       [  7, 300,   9]])

In [26]:
array2d

array([[100,  -3, 100],
       [  4, 200,   6],
       [  7, 300,   9]])

if we see that, changing b resulted changes in array2d it's because b is pointing to array2d rather making a copy of it. so we need to use copy()

In [27]:
b = array2d.copy()
b[0, 1] = 100
b

array([[100, 100, 100],
       [  4, 200,   6],
       [  7, 300,   9]])

In [28]:
array2d

array([[100,  -3, 100],
       [  4, 200,   6],
       [  7, 300,   9]])

now if we see that, b actually has a copy of array2d and we can modify the b matrix without affecting array2d

### Mathematics

In [29]:
# create a matrix of 3x3 with random integers between 0 and 20
a = np.random.randint(20, size=(3, 3))
a

array([[ 5, 16, 16],
       [ 2,  3, 18],
       [ 5,  9,  4]])

In [30]:
# add 2 to all elements
a+2

array([[ 7, 18, 18],
       [ 4,  5, 20],
       [ 7, 11,  6]])

In [31]:
a+a

array([[10, 32, 32],
       [ 4,  6, 36],
       [10, 18,  8]])

In [32]:
a**2 # square of all elements

array([[ 25, 256, 256],
       [  4,   9, 324],
       [ 25,  81,  16]])

In [33]:
# cosine of all elements
np.cos(a)

array([[ 0.28366219, -0.95765948, -0.95765948],
       [-0.41614684, -0.9899925 ,  0.66031671],
       [ 0.28366219, -0.91113026, -0.65364362]])

#### Linear Algebra

##### Matrix Multipication

In [34]:
c = np.random.randint(20, size=(2, 3))
d = np.random.randint(20, size=(3, 2))
np.matmul(c, d) # matrix multiplication

array([[490, 382],
       [440, 347]])

<h5>Inverse of a matrix</h5>

In [35]:
e = np.random.randint(20, size=(3, 3))
np.linalg.inv(e) # inverse of a matrix

array([[ 0.08      ,  0.22666667, -0.09333333],
       [ 0.        , -0.29166667,  0.08333333],
       [-0.04      ,  0.13666667,  0.04666667]])

<h5>Determinent of a matrix</h5>

In [36]:
np.linalg.det(e) # determinant of a matrix

-600.0

In [37]:
np.linalg.det(np.identity(3)) # determinant of a matrix

1.0

##### Solving a system of equations

$$3x-2y+5z = 10$$
$$x+6y+5z = 7$$
$$2x+5z = 16$$

In [38]:
A = np.array([[1, -2, 5], [1, 6, 5], [2, 0, 5]])
B = np.array([10, 7, 16])
np.linalg.solve(A, B) # solve a linear equation

array([ 6.75 , -0.375,  0.5  ])

In [39]:
#  to verify the solution of the 1st equation
np.sum(A[0] * [np.linalg.solve(A, B)]) # 10

10.0

### Reorganizing matrices

In [40]:
mat1 = np.random.randint(20, size=(3, 2))
mat1

array([[18, 19],
       [ 1,  6],
       [18,  8]])

In [41]:
# reshape a matrix
mat1.reshape(2, 3)

array([[18, 19,  1],
       [ 6, 18,  8]])

In [42]:
mat1.reshape(6, 1), mat1.reshape(1, 6)

(array([[18],
        [19],
        [ 1],
        [ 6],
        [18],
        [ 8]]),
 array([[18, 19,  1,  6, 18,  8]]))

#### dtype
dtype is an attribute of a numpy array, basically dtype allows us to specify the data type of our array.  
various numerical data types are:  
- int
  * int8
  * int16
  * int32
  * int64
- float
  * float16
  * float32
  * float64

by default the data type is of 64 bit.  
changing dtype attribute does benefit a lot in computations like when using lower bit data type it saves memory and obviously the computation is fast.


In [43]:
z = np.arange(10, dtype='int64')
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
z.nbytes

80

In [45]:
z = np.arange(10, dtype='int8')
z.nbytes

10

as we can see, if we changed from 64 bit to 8 bit, the size of the array is decreased